#TODO
#Get all content view inside
#for each content view inside
#  get latest version ID (components[*].content_view.next_version - 1 )
#  update composite view with latest version ID
- debug: msg="NOT DONE YET, Updating Composite Content View"
